/**
 * Semantic app icon contract.
 *
 * Every app-used action/state/navigation glyph is addressed by a stable
 * semantic name; per-pack adapters (Lucide, Tabler, Phosphor) resolve names to
 * bundled icon components. Theme files store a pack id only — never component
 * names, SVG data, or remote assets. Specialized artwork outside this system:
 * vscode-material-icons file glyphs, provider/product logos, MCP-provided
 * content icons, and Monaco editor icons.
 */

/** All semantic icon names understood by the app icon registry. */
export const APP_ICON_NAMES = [
  'activity',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'ban',
  'book',
  'bookmark',
  'bot',
  'case-sensitive',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-down-up',
  'chevrons-up-down',
  'circle',
  'circle-alert',
  'circle-check',
  'circle-check-big',
  'circle-dashed',
  'circle-dot',
  'circle-help',
  'circle-off',
  'circle-small',
  'circle-x',
  'clipboard-copy',
  'clipboard-paste',
  'clock',
  'code',
  'copy',
  'database',
  'download',
  'external-link',
  'eye',
  'eye-off',
  'file',
  'file-code',
  'file-plus',
  'file-search',
  'file-text',
  'filter',
  'folder',
  'folder-cog',
  'folder-open',
  'folder-plus',
  'folder-search',
  'folder-symlink',
  'git-branch',
  'git-commit',
  'git-compare-arrows',
  'git-fork',
  'globe',
  'grip-vertical',
  'hammer',
  'hard-drive',
  'hard-drive-upload',
  'image',
  'infinity',
  'info',
  'key-round',
  'keyboard',
  'list',
  'list-ordered',
  'list-todo',
  'loader',
  'log-in',
  'log-out',
  'mars',
  'mars-stroke',
  'message-circle',
  'message-circle-question',
  'message-square',
  'message-square-plus',
  'mic',
  'minus',
  'monitor',
  'moon',
  'more-horizontal',
  'music',
  'network',
  'non-binary',
  'octagon-x',
  'package',
  'package-x',
  'panel-left',
  'panel-left-close',
  'panel-right',
  'paperclip',
  'pause',
  'pencil',
  'pin',
  'pin-off',
  'play',
  'plus',
  'refresh-cw',
  'regex',
  'replace',
  'replace-all',
  'rotate-ccw',
  'save',
  'save-all',
  'scissors',
  'search',
  'server',
  'settings',
  'settings-2',
  'shield',
  'shield-alert',
  'shield-check',
  'shield-off',
  'sparkles',
  'square',
  'square-pen',
  'sun',
  'terminal',
  'transgender',
  'trash',
  'triangle-alert',
  'undo',
  'unlock',
  'upload',
  'venus',
  'venus-and-mars',
  'video',
  'wand',
  'wand-sparkles',
  'whole-word',
  'wifi',
  'wrap-text',
  'wrench',
  'x',
] as const

export type AppIconName = (typeof APP_ICON_NAMES)[number]

/** Semantic icon groups used by appearance previews. */
export type AppIconGroup = {
  label: string
  icons: readonly AppIconName[]
}

/** Navigation icons surfaced in icon-pack previews. */
export const APP_ICON_GROUP_NAVIGATION = [
  'folder',
  'folder-open',
  'folder-cog',
  'folder-plus',
  'folder-search',
  'folder-symlink',
  'search',
  'settings',
  'settings-2',
  'terminal',
  'file',
  'file-code',
  'file-plus',
  'file-search',
  'file-text',
  'panel-left',
  'panel-left-close',
  'panel-right',
  'globe',
  'bot',
  'message-square',
  'message-square-plus',
  'message-circle',
  'message-circle-question',
  'pin',
  'pin-off',
  'log-in',
  'log-out',
] as const satisfies readonly AppIconName[]

/** Actions icons surfaced in icon-pack previews. */
export const APP_ICON_GROUP_ACTIONS = [
  'plus',
  'minus',
  'pencil',
  'square-pen',
  'copy',
  'clipboard-copy',
  'clipboard-paste',
  'check',
  'x',
  'play',
  'pause',
  'save',
  'save-all',
  'download',
  'upload',
  'refresh-cw',
  'rotate-ccw',
  'undo',
  'scissors',
  'external-link',
  'replace',
  'replace-all',
  'filter',
  'eye',
  'eye-off',
  'keyboard',
  'wrench',
  'info',
  'grip-vertical',
  'hammer',
  'list',
  'list-ordered',
  'list-todo',
  'case-sensitive',
  'regex',
  'whole-word',
  'wrap-text',
  'square',
  'code',
  'sparkles',
  'wand',
  'wand-sparkles',
  'mic',
  'image',
  'video',
  'music',
  'moon',
  'sun',
  'monitor',
  'server',
  'network',
  'database',
  'mars',
  'mars-stroke',
  'non-binary',
  'transgender',
  'venus',
  'venus-and-mars',
  'paperclip',
  'package',
  'package-x',
  'hard-drive',
  'hard-drive-upload',
  'key-round',
  'unlock',
  'git-commit',
  'git-compare-arrows',
  'book',
  'bookmark',
  'more-horizontal',
] as const satisfies readonly AppIconName[]

/** Status icons surfaced in icon-pack previews. */
export const APP_ICON_GROUP_STATUS = [
  'circle-check',
  'circle-check-big',
  'circle-alert',
  'triangle-alert',
  'circle-x',
  'circle-dashed',
  'circle-dot',
  'clock',
  'loader',
  'ban',
  'shield',
  'shield-check',
  'shield-off',
  'shield-alert',
  'infinity',
  'activity',
  'wifi',
  'circle-off',
  'circle-small',
  'circle-help',
  'circle',
] as const satisfies readonly AppIconName[]

/** Directional icons surfaced in icon-pack previews. */
export const APP_ICON_GROUP_DIRECTIONAL = [
  'arrow-up',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'chevron-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevrons-up-down',
  'chevrons-down-up',
  'git-branch',
  'git-fork',
  'folder-open',
] as const satisfies readonly AppIconName[]

/** Destructive icons surfaced in icon-pack previews. */
export const APP_ICON_GROUP_DESTRUCTIVE = [
  'trash',
  'circle-x',
  'ban',
  'shield-off',
  'scissors',
  'x',
  'octagon-x',
  'package-x',
] as const satisfies readonly AppIconName[]

/** Ordered icon-pack preview groups (navigation, actions, status, ...). */
export const APP_ICON_PREVIEW_GROUPS: readonly AppIconGroup[] = [
  { label: 'Navigation', icons: APP_ICON_GROUP_NAVIGATION },
  { label: 'Actions', icons: APP_ICON_GROUP_ACTIONS },
  { label: 'Status', icons: APP_ICON_GROUP_STATUS },
  { label: 'Directional', icons: APP_ICON_GROUP_DIRECTIONAL },
  { label: 'Destructive', icons: APP_ICON_GROUP_DESTRUCTIVE },
]
