import type { VixlChatMode } from '@/types/vixl/vixl-settings'

const BROWSER_TOOLS = [
  'browser_tabs',
  'browser_navigate',
  'browser_lock',
  'browser_snapshot',
  'browser_take_screenshot',
  'browser_click',
  'browser_mouse_click_xy',
  'browser_type',
  'browser_fill',
  'browser_select_option',
  'browser_press_key',
  'browser_scroll',
  'browser_drag',
  'browser_get_bounding_box',
  'browser_highlight',
  'browser_cdp',
] as const

const MCP_TOOLS = [
  'call_mcp_tool',
  'get_mcp_tools',
  'list_mcp_resources',
  'read_mcp_resource',
  'get_mcp_prompt',
] as const

const ASK_TOOLS = [
  'read_file',
  'grep',
  'glob_files',
  'list_dir',
  'codebase_explore',
  'codebase_search',
  'codebase_impact',
  'codebase_status',
  'git_status',
  'git_diff',
  'git_log',
  'git_branch',
  'lsp',
  'diagnostics',
  'load_skill',
  'ask_user',
  'web_fetch',
  ...MCP_TOOLS,
  ...BROWSER_TOOLS,
  'spawn_subagent',
  'resolve_models',
] as const

const PLAN_TOOLS = [
  ...ASK_TOOLS,
  'create_plan',
  'update_plan_todo',
] as const

const ORCHESTRATOR_TOOLS = [
  'read_file',
  'list_dir',
  'grep',
  'glob_files',
  'codebase_explore',
  'codebase_search',
  'codebase_impact',
  'codebase_status',
  'git_status',
  'git_diff',
  'git_log',
  'git_branch',
  'lsp',
  'diagnostics',
  'load_skill',
  'ask_user',
  'web_fetch',
  'call_mcp_tool',
  'get_mcp_tools',
  'list_mcp_resources',
  'read_mcp_resource',
  'get_mcp_prompt',
  'create_plan',
  'update_plan_todo',
  'update_todos',
  'spawn_subagent',
  'resolve_models',
  ...BROWSER_TOOLS,
] as const

export const MODE_TOOL_ALLOWLIST: Record<VixlChatMode, string[]> = {
  ask: [...ASK_TOOLS],
  plan: [...PLAN_TOOLS],
  studio: [
    ...PLAN_TOOLS,
    'run_terminal',
    'terminal_output',
    'stop_terminal',
    'write_studio_artifact',
    'call_mcp_tool',
    'get_mcp_tools',
    'list_mcp_resources',
    'read_mcp_resource',
    'get_mcp_prompt',
    ...BROWSER_TOOLS,
    'spawn_subagent',
    'resolve_models',
  ],
  agent: [
    'read_file',
    'write_file',
    'edit_file',
    'apply_patch',
    'delete_file',
    'move_file',
    'grep',
    'glob_files',
    'list_dir',
    'codebase_explore',
    'codebase_search',
    'codebase_impact',
    'codebase_status',
    'git_status',
    'git_diff',
    'git_log',
    'git_branch',
    'git_checkout',
    'git_branch_create',
    'git_commit',
    'lsp',
    'diagnostics',
    'run_terminal',
    'terminal_output',
    'stop_terminal',
    'load_skill',
    'ask_user',
    'web_fetch',
    'call_mcp_tool',
    'get_mcp_tools',
    'list_mcp_resources',
    'read_mcp_resource',
    'get_mcp_prompt',
    'create_plan',
    'update_plan_todo',
    'update_todos',
    'write_studio_artifact',
    'spawn_subagent',
    'resolve_models',
    ...BROWSER_TOOLS,
  ],
  orchestrator: [...ORCHESTRATOR_TOOLS],
}

export const filterToolsByMode = <T extends { name: string }>(
  mode: VixlChatMode,
  tools: T[],
): T[] => {
  const allow = new Set(MODE_TOOL_ALLOWLIST[mode])
  return tools.filter((tool) => allow.has(tool.name))
}
