export const TOOL_DESCRIPTIONS: Record<string, string> = {
  read_file: 'Read a file from the project workspace',
  write_file: 'Create or overwrite a file',
  edit_file: 'Edit a file with search/replace',
  apply_patch: 'Apply an OpenCode-style multi-file patch',
  delete_file: 'Delete a file from the workspace',
  move_file: 'Move or rename a workspace file',
  list_dir: 'List directory contents',
  glob_files: 'Find files by glob pattern',
  grep: 'Search file contents with regex',
  codebase_explore: 'Explore CodeGraph for architecture, flows, and structural context',
  codebase_search: 'Search CodeGraph symbols by name (locations only)',
  codebase_impact: 'Analyze CodeGraph blast radius for a symbol change',
  codebase_status: 'Check CodeGraph index health and sync status',
  git_status: 'Show git working tree status',
  git_diff: 'Show git diff',
  git_log: 'Show git commit history',
  git_branch: 'Show current git branch',
  git_checkout: 'Checkout a git branch or ref',
  git_branch_create: 'Create a new git branch',
  git_commit: 'Stage and commit changes',
  lsp: 'Query language server (goToDefinition, findReferences, hover, symbols, workspaceSymbol, diagnostics). Use 0-based position for defs/refs/hover and query for workspaceSymbol. Prefer codebase_* for structural discovery; prefer over grep for precise symbols.',
  diagnostics: 'Read linter and diagnostic errors for a file',
  run_terminal: 'Run a shell command in the project',
  terminal_output: 'Read output from a background agent shell (not subagent ids)',
  stop_terminal: 'Stop a background agent shell',
  load_skill: 'Load a project skill by name',
  ask_user: 'Ask the user a clarifying question',
  call_mcp_tool: 'Invoke a tool on a configured MCP server',
  get_mcp_tools: 'List configured MCP servers and their tools',
  list_mcp_resources: 'List resources from a connected HTTP or SSE MCP server',
  read_mcp_resource: 'Read a resource URI from an MCP server',
  get_mcp_prompt: 'Retrieve a prompt template from an MCP server',
  create_plan: 'Create a plan document',
  update_plan_todo: 'Update a plan todo item',
  update_todos: 'Create, update, complete, cancel, or remove in-chat todos (full list)',
  write_studio_artifact: 'Write a studio artifact',
  spawn_subagent: 'Spawn sub-agent (background: end turn, harness resumes)',
  resolve_models:
    'Look up allowed model refs by query and optional provider (capped)',
  web_fetch:
    'Fetch an http(s) URL as markdown, text, or html (plain HTTP GET, no JavaScript)',
}
