/**
 * Lucide adapter for the semantic app icon registry.
 *
 * Explicit named imports only (tree-shaking keeps unmapped glyphs out of the
 * bundle). Never re-export the package namespace or resolve icons dynamically
 * from string package exports; extend this map instead. Some semantic names
 * intentionally map to the nearest equivalent glyph in this pack.
 */
import type { Component } from 'vue'
import type { AppIconName } from '../icon-names'
import type { IconPackAdapter } from './types'
import { normalizeIconWeight } from './types'
import {
  ActivityIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BanIcon,
  BookIcon,
  BookmarkIcon,
  BotIcon,
  CaseSensitiveIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronsDownUpIcon,
  ChevronsUpDownIcon,
  CircleIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  CircleCheckBigIcon,
  CircleDashedIcon,
  CircleDotIcon,
  CircleHelpIcon,
  CircleOffIcon,
  CircleSmallIcon,
  CircleXIcon,
  ClipboardCopyIcon,
  ClipboardPasteIcon,
  ClockIcon,
  CodeIcon,
  CopyIcon,
  DatabaseIcon,
  DownloadIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FileCodeIcon,
  FilePlusIcon,
  FileSearchIcon,
  FileTextIcon,
  FilterIcon,
  FolderIcon,
  FolderCogIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderSearchIcon,
  FolderSymlinkIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitCompareArrowsIcon,
  GitForkIcon,
  GlobeIcon,
  GripVerticalIcon,
  HammerIcon,
  HardDriveIcon,
  HardDriveUploadIcon,
  ImageIcon,
  InfinityIcon,
  InfoIcon,
  KeyRoundIcon,
  KeyboardIcon,
  ListIcon,
  ListOrderedIcon,
  ListTodoIcon,
  LoaderIcon,
  LogInIcon,
  LogOutIcon,
  MarsIcon,
  MarsStrokeIcon,
  MessageCircleIcon,
  MessageCircleQuestionIcon,
  MessageSquareIcon,
  MessageSquarePlusIcon,
  MicIcon,
  MinusIcon,
  MonitorIcon,
  MoonIcon,
  MoreHorizontalIcon,
  MusicIcon,
  NetworkIcon,
  NonBinaryIcon,
  OctagonXIcon,
  PackageIcon,
  PackageXIcon,
  PanelLeftIcon,
  PanelLeftCloseIcon,
  PanelRightIcon,
  PaperclipIcon,
  PauseIcon,
  PencilIcon,
  PinIcon,
  PinOffIcon,
  PlayIcon,
  PlusIcon,
  RefreshCwIcon,
  RegexIcon,
  ReplaceIcon,
  ReplaceAllIcon,
  RotateCcwIcon,
  SaveIcon,
  SaveAllIcon,
  ScissorsIcon,
  SearchIcon,
  ServerIcon,
  SettingsIcon,
  Settings2Icon,
  ShieldIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShieldOffIcon,
  SparklesIcon,
  SquareIcon,
  SquarePenIcon,
  SunIcon,
  TerminalIcon,
  TransgenderIcon,
  TrashIcon,
  TriangleAlertIcon,
  UndoIcon,
  UnlockIcon,
  UploadIcon,
  VenusIcon,
  VenusAndMarsIcon,
  VideoIcon,
  WandIcon,
  WandSparklesIcon,
  WholeWordIcon,
  WifiIcon,
  WrapTextIcon,
  WrenchIcon,
  XIcon,
} from '@lucide/vue'

export const lucideIconComponents: Record<AppIconName, Component> = {
  activity: ActivityIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-up': ArrowUpIcon,
  ban: BanIcon,
  book: BookIcon,
  bookmark: BookmarkIcon,
  bot: BotIcon,
  'case-sensitive': CaseSensitiveIcon,
  check: CheckIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'chevrons-down-up': ChevronsDownUpIcon,
  'chevrons-up-down': ChevronsUpDownIcon,
  circle: CircleIcon,
  'circle-alert': CircleAlertIcon,
  'circle-check': CircleCheckIcon,
  'circle-check-big': CircleCheckBigIcon,
  'circle-dashed': CircleDashedIcon,
  'circle-dot': CircleDotIcon,
  'circle-help': CircleHelpIcon,
  'circle-off': CircleOffIcon,
  'circle-small': CircleSmallIcon,
  'circle-x': CircleXIcon,
  'clipboard-copy': ClipboardCopyIcon,
  'clipboard-paste': ClipboardPasteIcon,
  clock: ClockIcon,
  code: CodeIcon,
  copy: CopyIcon,
  database: DatabaseIcon,
  download: DownloadIcon,
  'external-link': ExternalLinkIcon,
  eye: EyeIcon,
  'eye-off': EyeOffIcon,
  file: FileIcon,
  'file-code': FileCodeIcon,
  'file-plus': FilePlusIcon,
  'file-search': FileSearchIcon,
  'file-text': FileTextIcon,
  filter: FilterIcon,
  folder: FolderIcon,
  'folder-cog': FolderCogIcon,
  'folder-open': FolderOpenIcon,
  'folder-plus': FolderPlusIcon,
  'folder-search': FolderSearchIcon,
  'folder-symlink': FolderSymlinkIcon,
  'git-branch': GitBranchIcon,
  'git-commit': GitCommitIcon,
  'git-compare-arrows': GitCompareArrowsIcon,
  'git-fork': GitForkIcon,
  globe: GlobeIcon,
  'grip-vertical': GripVerticalIcon,
  hammer: HammerIcon,
  'hard-drive': HardDriveIcon,
  'hard-drive-upload': HardDriveUploadIcon,
  image: ImageIcon,
  infinity: InfinityIcon,
  info: InfoIcon,
  'key-round': KeyRoundIcon,
  keyboard: KeyboardIcon,
  list: ListIcon,
  'list-ordered': ListOrderedIcon,
  'list-todo': ListTodoIcon,
  loader: LoaderIcon,
  'log-in': LogInIcon,
  'log-out': LogOutIcon,
  mars: MarsIcon,
  'mars-stroke': MarsStrokeIcon,
  'message-circle': MessageCircleIcon,
  'message-circle-question': MessageCircleQuestionIcon,
  'message-square': MessageSquareIcon,
  'message-square-plus': MessageSquarePlusIcon,
  mic: MicIcon,
  minus: MinusIcon,
  monitor: MonitorIcon,
  moon: MoonIcon,
  'more-horizontal': MoreHorizontalIcon,
  music: MusicIcon,
  network: NetworkIcon,
  'non-binary': NonBinaryIcon,
  'octagon-x': OctagonXIcon,
  package: PackageIcon,
  'package-x': PackageXIcon,
  'panel-left': PanelLeftIcon,
  'panel-left-close': PanelLeftCloseIcon,
  'panel-right': PanelRightIcon,
  paperclip: PaperclipIcon,
  pause: PauseIcon,
  pencil: PencilIcon,
  pin: PinIcon,
  'pin-off': PinOffIcon,
  play: PlayIcon,
  plus: PlusIcon,
  'refresh-cw': RefreshCwIcon,
  regex: RegexIcon,
  replace: ReplaceIcon,
  'replace-all': ReplaceAllIcon,
  'rotate-ccw': RotateCcwIcon,
  save: SaveIcon,
  'save-all': SaveAllIcon,
  scissors: ScissorsIcon,
  search: SearchIcon,
  server: ServerIcon,
  settings: SettingsIcon,
  'settings-2': Settings2Icon,
  shield: ShieldIcon,
  'shield-alert': ShieldAlertIcon,
  'shield-check': ShieldCheckIcon,
  'shield-off': ShieldOffIcon,
  sparkles: SparklesIcon,
  square: SquareIcon,
  'square-pen': SquarePenIcon,
  sun: SunIcon,
  terminal: TerminalIcon,
  transgender: TransgenderIcon,
  trash: TrashIcon,
  'triangle-alert': TriangleAlertIcon,
  undo: UndoIcon,
  unlock: UnlockIcon,
  upload: UploadIcon,
  venus: VenusIcon,
  'venus-and-mars': VenusAndMarsIcon,
  video: VideoIcon,
  wand: WandIcon,
  'wand-sparkles': WandSparklesIcon,
  'whole-word': WholeWordIcon,
  wifi: WifiIcon,
  'wrap-text': WrapTextIcon,
  wrench: WrenchIcon,
  x: XIcon,
}

export const lucideIconAdapter: IconPackAdapter = {
  id: 'lucide',
  components: lucideIconComponents,
  strokeProps: (weight) => ({ ['stroke-width']: normalizeIconWeight(weight) }),
}
