/**
 * Phosphor adapter for the semantic app icon registry.
 *
 * Explicit named imports only (tree-shaking keeps unmapped glyphs out of the
 * bundle). Never re-export the package namespace or resolve icons dynamically
 * from string package exports; extend this map instead. Some semantic names
 * intentionally map to the nearest equivalent glyph in this pack.
 */
import type { Component } from 'vue'
import type { AppIconName } from '../icon-names'
import type { IconPackAdapter } from './types'
import { phosphorWeightFor } from './types'
import {
  PhActivity,
  PhArrowDown,
  PhArrowLeft,
  PhArrowRight,
  PhArrowUp,
  PhProhibit,
  PhBook,
  PhBookmark,
  PhRobot,
  PhTextAa,
  PhCheck,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhCaretUp,
  PhCaretDoubleDown,
  PhCaretCircleUpDown,
  PhCircle,
  PhWarningCircle,
  PhCheckCircle,
  PhCircleDashed,
  PhRecord,
  PhQuestion,
  PhXCircle,
  PhClipboardText,
  PhClock,
  PhCode,
  PhCopy,
  PhDatabase,
  PhDownload,
  PhArrowSquareOut,
  PhEye,
  PhEyeSlash,
  PhFile,
  PhFileCode,
  PhFilePlus,
  PhFileSearch,
  PhFileText,
  PhFunnel,
  PhFolder,
  PhFolders,
  PhFolderOpen,
  PhFolderPlus,
  PhLink,
  PhGitBranch,
  PhGitCommit,
  PhGitDiff,
  PhGitFork,
  PhGlobe,
  PhDotsSixVertical,
  PhHammer,
  PhHardDrive,
  PhHardDrives,
  PhImage,
  PhInfinity,
  PhInfo,
  PhKey,
  PhKeyboard,
  PhList,
  PhListNumbers,
  PhListChecks,
  PhCircleNotch,
  PhSignIn,
  PhSignOut,
  PhGenderMale,
  PhGenderTransgender,
  PhChatCircle,
  PhChatCircleDots,
  PhChat,
  PhMicrophone,
  PhMinus,
  PhMonitor,
  PhMoon,
  PhDotsThree,
  PhMusicNotes,
  PhNetwork,
  PhGenderNonbinary,
  PhPackage,
  PhSidebarSimple,
  PhSidebar,
  PhPaperclip,
  PhPause,
  PhPencil,
  PhPushPin,
  PhPushPinSlash,
  PhPlay,
  PhPlus,
  PhArrowsClockwise,
  PhAsterisk,
  PhArrowsLeftRight,
  PhArrowsOut,
  PhArrowCounterClockwise,
  PhFloppyDisk,
  PhFloppyDiskBack,
  PhScissors,
  PhMagnifyingGlass,
  PhGear,
  PhSliders,
  PhShield,
  PhShieldWarning,
  PhShieldCheck,
  PhShieldSlash,
  PhSparkle,
  PhSquare,
  PhPencilSimple,
  PhSun,
  PhTerminalWindow,
  PhTrash,
  PhWarning,
  PhLockOpen,
  PhUpload,
  PhGenderFemale,
  PhGenderIntersex,
  PhVideo,
  PhMagicWand,
  PhWifiHigh,
  PhTextIndent,
  PhWrench,
  PhX,
} from '@phosphor-icons/vue'

export const phosphorIconComponents: Record<AppIconName, Component> = {
  activity: PhActivity,
  'arrow-down': PhArrowDown,
  'arrow-left': PhArrowLeft,
  'arrow-right': PhArrowRight,
  'arrow-up': PhArrowUp,
  ban: PhProhibit,
  book: PhBook,
  bookmark: PhBookmark,
  bot: PhRobot,
  'case-sensitive': PhTextAa,
  check: PhCheck,
  'chevron-down': PhCaretDown,
  'chevron-left': PhCaretLeft,
  'chevron-right': PhCaretRight,
  'chevron-up': PhCaretUp,
  'chevrons-down-up': PhCaretDoubleDown,
  'chevrons-up-down': PhCaretCircleUpDown,
  circle: PhCircle,
  'circle-alert': PhWarningCircle,
  'circle-check': PhCheckCircle,
  'circle-check-big': PhCheckCircle,
  'circle-dashed': PhCircleDashed,
  'circle-dot': PhRecord,
  'circle-help': PhQuestion,
  'circle-off': PhCircleDashed,
  'circle-small': PhCircle,
  'circle-x': PhXCircle,
  'clipboard-copy': PhClipboardText,
  'clipboard-paste': PhClipboardText,
  clock: PhClock,
  code: PhCode,
  copy: PhCopy,
  database: PhDatabase,
  download: PhDownload,
  'external-link': PhArrowSquareOut,
  eye: PhEye,
  'eye-off': PhEyeSlash,
  file: PhFile,
  'file-code': PhFileCode,
  'file-plus': PhFilePlus,
  'file-search': PhFileSearch,
  'file-text': PhFileText,
  filter: PhFunnel,
  folder: PhFolder,
  'folder-cog': PhFolders,
  'folder-open': PhFolderOpen,
  'folder-plus': PhFolderPlus,
  'folder-search': PhFolder,
  'folder-symlink': PhLink,
  'git-branch': PhGitBranch,
  'git-commit': PhGitCommit,
  'git-compare-arrows': PhGitDiff,
  'git-fork': PhGitFork,
  globe: PhGlobe,
  'grip-vertical': PhDotsSixVertical,
  hammer: PhHammer,
  'hard-drive': PhHardDrive,
  'hard-drive-upload': PhHardDrives,
  image: PhImage,
  infinity: PhInfinity,
  info: PhInfo,
  'key-round': PhKey,
  keyboard: PhKeyboard,
  list: PhList,
  'list-ordered': PhListNumbers,
  'list-todo': PhListChecks,
  loader: PhCircleNotch,
  'log-in': PhSignIn,
  'log-out': PhSignOut,
  mars: PhGenderMale,
  'mars-stroke': PhGenderTransgender,
  'message-circle': PhChatCircle,
  'message-circle-question': PhChatCircleDots,
  'message-square': PhChat,
  'message-square-plus': PhChat,
  mic: PhMicrophone,
  minus: PhMinus,
  monitor: PhMonitor,
  moon: PhMoon,
  'more-horizontal': PhDotsThree,
  music: PhMusicNotes,
  network: PhNetwork,
  'non-binary': PhGenderNonbinary,
  'octagon-x': PhXCircle,
  package: PhPackage,
  'package-x': PhProhibit,
  'panel-left': PhSidebarSimple,
  'panel-left-close': PhSidebarSimple,
  'panel-right': PhSidebar,
  paperclip: PhPaperclip,
  pause: PhPause,
  pencil: PhPencil,
  pin: PhPushPin,
  'pin-off': PhPushPinSlash,
  play: PhPlay,
  plus: PhPlus,
  'refresh-cw': PhArrowsClockwise,
  regex: PhAsterisk,
  replace: PhArrowsLeftRight,
  'replace-all': PhArrowsOut,
  'rotate-ccw': PhArrowCounterClockwise,
  save: PhFloppyDisk,
  'save-all': PhFloppyDiskBack,
  scissors: PhScissors,
  search: PhMagnifyingGlass,
  server: PhHardDrives,
  settings: PhGear,
  'settings-2': PhSliders,
  shield: PhShield,
  'shield-alert': PhShieldWarning,
  'shield-check': PhShieldCheck,
  'shield-off': PhShieldSlash,
  sparkles: PhSparkle,
  square: PhSquare,
  'square-pen': PhPencilSimple,
  sun: PhSun,
  terminal: PhTerminalWindow,
  transgender: PhGenderTransgender,
  trash: PhTrash,
  'triangle-alert': PhWarning,
  undo: PhArrowCounterClockwise,
  unlock: PhLockOpen,
  upload: PhUpload,
  venus: PhGenderFemale,
  'venus-and-mars': PhGenderIntersex,
  video: PhVideo,
  wand: PhMagicWand,
  'wand-sparkles': PhMagicWand,
  'whole-word': PhTextAa,
  wifi: PhWifiHigh,
  'wrap-text': PhTextIndent,
  wrench: PhWrench,
  x: PhX,
}

export const phosphorIconAdapter: IconPackAdapter = {
  id: 'phosphor',
  components: phosphorIconComponents,
  strokeProps: (weight) => ({ weight: phosphorWeightFor(weight) }),
}
