/**
 * Tabler adapter for the semantic app icon registry.
 *
 * Explicit named imports only (tree-shaking keeps unmapped glyphs out of the
 * bundle). Never re-export the package namespace or resolve icons dynamically
 * from string package exports; extend this map instead. Some semantic names
 * intentionally map to the nearest equivalent glyph in this pack.
 */
import type { Component } from 'vue'
import type { AppIconName } from '../icon-names'
import type { IconPackAdapter } from './types'
import { normalizeIconWeight } from './types'
import {
  IconActivity,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBan,
  IconBook,
  IconBookmark,
  IconRobot,
  IconLetterCase,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCaretUpDown,
  IconCircle,
  IconAlertCircle,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleDot,
  IconHelpCircle,
  IconCircleOff,
  IconPoint,
  IconCircleX,
  IconClipboardCopy,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCopy,
  IconDatabase,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileCode,
  IconFilePlus,
  IconFileSearch,
  IconFileText,
  IconFilter,
  IconFolder,
  IconFolderCog,
  IconFolderOpen,
  IconFolderPlus,
  IconFolderSearch,
  IconFolderSymlink,
  IconGitBranch,
  IconGitCommit,
  IconGitCompare,
  IconGitFork,
  IconGlobe,
  IconGripVertical,
  IconHammer,
  IconDatabaseExport,
  IconPhoto,
  IconInfinity,
  IconInfoCircle,
  IconKey,
  IconKeyboard,
  IconList,
  IconListNumbers,
  IconListCheck,
  IconLoader,
  IconLogin,
  IconLogout,
  IconMars,
  IconGenderTransgender,
  IconMessageCircle,
  IconMessageCircleQuestion,
  IconMessage,
  IconMessagePlus,
  IconMicrophone,
  IconMinus,
  IconDeviceDesktop,
  IconMoon,
  IconDots,
  IconMusic,
  IconNetwork,
  IconGenderAgender,
  IconPackage,
  IconPackageOff,
  IconLayoutSidebar,
  IconLayoutSidebarRight,
  IconPaperclip,
  IconPlayerPause,
  IconPencil,
  IconPinned,
  IconPinnedOff,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconRegex,
  IconReplace,
  IconArrowsExchange,
  IconRotate2,
  IconDeviceFloppy,
  IconScissors,
  IconSearch,
  IconServer,
  IconSettings,
  IconAdjustments,
  IconShield,
  IconShieldExclamation,
  IconShieldCheck,
  IconShieldOff,
  IconSparkles,
  IconSquare,
  IconSun,
  IconTerminal,
  IconTrash,
  IconAlertTriangle,
  IconArrowBackUp,
  IconLockOpen,
  IconUpload,
  IconVenus,
  IconGenderBigender,
  IconVideo,
  IconWand,
  IconWifi,
  IconTextWrap,
  IconTool,
  IconX,
} from '@tabler/icons-vue'

export const tablerIconComponents: Record<AppIconName, Component> = {
  activity: IconActivity,
  'arrow-down': IconArrowDown,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'arrow-up': IconArrowUp,
  ban: IconBan,
  book: IconBook,
  bookmark: IconBookmark,
  bot: IconRobot,
  'case-sensitive': IconLetterCase,
  check: IconCheck,
  'chevron-down': IconChevronDown,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'chevron-up': IconChevronUp,
  'chevrons-down-up': IconCaretUpDown,
  'chevrons-up-down': IconCaretUpDown,
  circle: IconCircle,
  'circle-alert': IconAlertCircle,
  'circle-check': IconCircleCheck,
  'circle-check-big': IconCircleCheck,
  'circle-dashed': IconCircleDashed,
  'circle-dot': IconCircleDot,
  'circle-help': IconHelpCircle,
  'circle-off': IconCircleOff,
  'circle-small': IconPoint,
  'circle-x': IconCircleX,
  'clipboard-copy': IconClipboardCopy,
  'clipboard-paste': IconClipboardText,
  clock: IconClock,
  code: IconCode,
  copy: IconCopy,
  database: IconDatabase,
  download: IconDownload,
  'external-link': IconExternalLink,
  eye: IconEye,
  'eye-off': IconEyeOff,
  file: IconFile,
  'file-code': IconFileCode,
  'file-plus': IconFilePlus,
  'file-search': IconFileSearch,
  'file-text': IconFileText,
  filter: IconFilter,
  folder: IconFolder,
  'folder-cog': IconFolderCog,
  'folder-open': IconFolderOpen,
  'folder-plus': IconFolderPlus,
  'folder-search': IconFolderSearch,
  'folder-symlink': IconFolderSymlink,
  'git-branch': IconGitBranch,
  'git-commit': IconGitCommit,
  'git-compare-arrows': IconGitCompare,
  'git-fork': IconGitFork,
  globe: IconGlobe,
  'grip-vertical': IconGripVertical,
  hammer: IconHammer,
  'hard-drive': IconDatabase,
  'hard-drive-upload': IconDatabaseExport,
  image: IconPhoto,
  infinity: IconInfinity,
  info: IconInfoCircle,
  'key-round': IconKey,
  keyboard: IconKeyboard,
  list: IconList,
  'list-ordered': IconListNumbers,
  'list-todo': IconListCheck,
  loader: IconLoader,
  'log-in': IconLogin,
  'log-out': IconLogout,
  mars: IconMars,
  'mars-stroke': IconGenderTransgender,
  'message-circle': IconMessageCircle,
  'message-circle-question': IconMessageCircleQuestion,
  'message-square': IconMessage,
  'message-square-plus': IconMessagePlus,
  mic: IconMicrophone,
  minus: IconMinus,
  monitor: IconDeviceDesktop,
  moon: IconMoon,
  'more-horizontal': IconDots,
  music: IconMusic,
  network: IconNetwork,
  'non-binary': IconGenderAgender,
  'octagon-x': IconCircleX,
  package: IconPackage,
  'package-x': IconPackageOff,
  'panel-left': IconLayoutSidebar,
  'panel-left-close': IconLayoutSidebar,
  'panel-right': IconLayoutSidebarRight,
  paperclip: IconPaperclip,
  pause: IconPlayerPause,
  pencil: IconPencil,
  pin: IconPinned,
  'pin-off': IconPinnedOff,
  play: IconPlayerPlay,
  plus: IconPlus,
  'refresh-cw': IconRefresh,
  regex: IconRegex,
  replace: IconReplace,
  'replace-all': IconArrowsExchange,
  'rotate-ccw': IconRotate2,
  save: IconDeviceFloppy,
  'save-all': IconDeviceFloppy,
  scissors: IconScissors,
  search: IconSearch,
  server: IconServer,
  settings: IconSettings,
  'settings-2': IconAdjustments,
  shield: IconShield,
  'shield-alert': IconShieldExclamation,
  'shield-check': IconShieldCheck,
  'shield-off': IconShieldOff,
  sparkles: IconSparkles,
  square: IconSquare,
  'square-pen': IconPencil,
  sun: IconSun,
  terminal: IconTerminal,
  transgender: IconGenderTransgender,
  trash: IconTrash,
  'triangle-alert': IconAlertTriangle,
  undo: IconArrowBackUp,
  unlock: IconLockOpen,
  upload: IconUpload,
  venus: IconVenus,
  'venus-and-mars': IconGenderBigender,
  video: IconVideo,
  wand: IconWand,
  'wand-sparkles': IconWand,
  'whole-word': IconLetterCase,
  wifi: IconWifi,
  'wrap-text': IconTextWrap,
  wrench: IconTool,
  x: IconX,
}

export const tablerIconAdapter: IconPackAdapter = {
  id: 'tabler',
  components: tablerIconComponents,
  strokeProps: (weight) => ({ ['strokeWidth']: normalizeIconWeight(weight) }),
}
