import { bundledGlass, bundledIcons, makeBundledTheme, stops, type BundledThemeSpec } from './theme-builder'

/**
 * Cyber Lime — dark graphite with lime/violet technical accents.
 * Original palette inspired generically by terminal/tech aesthetics.
 */
const spec: BundledThemeSpec = {
  id: 'cyber-lime',
  name: 'Cyber Lime',
  light: {
    colors: {
      background: '#f4f4f2',
      foreground: '#1d1d22',
      card: '#ffffff',
      cardForeground: '#1d1d22',
      popover: '#ffffff',
      popoverForeground: '#1d1d22',
      primary: '#4d7c0f',
      primaryForeground: '#ffffff',
      secondary: '#e9eae4',
      secondaryForeground: '#3a4212',
      muted: '#ecede7',
      mutedForeground: '#5d5f55',
      accent: '#e2e5d4',
      accentForeground: '#3a4212',
      destructive: '#b91c1c',
      border: '#d6d7cd',
      input: '#d6d7cd',
      ring: '#4d7c0f',
      sidebar: '#edeee8',
      sidebarForeground: '#1d1d22',
      sidebarPrimary: '#4d7c0f',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#e2e5d4',
      sidebarAccentForeground: '#3a4212',
      sidebarBorder: '#d6d7cd',
      sidebarRing: '#4d7c0f',
      chart1: '#65a30d',
      chart2: '#7c3aed',
      chart3: '#0d9488',
      chart4: '#d97706',
      chart5: '#dc2626',
    },
    editor: {
      background: '#f7f7f4',
      foreground: '#232328',
      comment: '#7d7f72',
      keyword: '#4d7c0f',
      keywordAccent: '#6d3ac2',
      string: '#3d7a3a',
      number: '#9a6a1e',
      function: '#6b6b2a',
      type: '#2a7a70',
      variable: '#45484a',
      constant: '#5f4ac2',
      operator: '#4c4e44',
      invalid: '#b91c1c',
      regexp: '#6d3ac2',
      attribute: '#45484a',
      tag: '#4d7c0f',
      escape: '#7a5c2a',
    },
    canvas: {
      fallback: '#f4f4f2',
      layers: [
        {
          kind: 'conic',
          angle: 220,
          x: 80,
          y: 0,
          stops: stops(['#a3e63522', 0], ['#f4f4f200', 45]),
        },
      ],
    },
    glass: bundledGlass(['panels'], {
      surfaceOpacity: 74,
      blur: 14,
      saturation: 130,
      borderOpacity: 26,
      shadow: 'none',
      radius: 'sm',
    }),
  },
  dark: {
    colors: {
      background: '#101014',
      foreground: '#e8e8ee',
      card: '#18181f',
      cardForeground: '#e8e8ee',
      popover: '#18181f',
      popoverForeground: '#e8e8ee',
      primary: '#a3e635',
      primaryForeground: '#101014',
      secondary: '#1f1f28',
      secondaryForeground: '#d4d4e0',
      muted: '#1c1c24',
      mutedForeground: '#9c9caa',
      accent: '#26262f',
      accentForeground: '#e8e8ee',
      destructive: '#fb7185',
      border: '#2c2c38',
      input: '#2c2c38',
      ring: '#a3e635',
      sidebar: '#131318',
      sidebarForeground: '#e8e8ee',
      sidebarPrimary: '#a3e635',
      sidebarPrimaryForeground: '#101014',
      sidebarAccent: '#1f1f28',
      sidebarAccentForeground: '#e8e8ee',
      sidebarBorder: '#24242e',
      sidebarRing: '#a3e635',
      chart1: '#a3e635',
      chart2: '#a78bfa',
      chart3: '#2dd4bf',
      chart4: '#fbbf24',
      chart5: '#fb7185',
    },
    editor: {
      background: '#121218',
      foreground: '#dcdce6',
      comment: '#6f7080',
      keyword: '#a3e635',
      keywordAccent: '#b79dfa',
      string: '#8ac87a',
      number: '#e0b060',
      function: '#c8c87a',
      type: '#70c8b8',
      variable: '#c0c2cc',
      constant: '#a89af0',
      operator: '#8f91a0',
      invalid: '#fb7185',
      regexp: '#b79dfa',
      attribute: '#c0c2cc',
      tag: '#a3e635',
      escape: '#d0b080',
    },
    canvas: {
      fallback: '#101014',
      layers: [
        {
          kind: 'conic',
          angle: 200,
          x: 85,
          y: 5,
          stops: stops(['#65a30d33', 0], ['#10101400', 40]),
        },
        {
          kind: 'radial',
          x: 10,
          y: 95,
          size: 'farthest-side',
          stops: stops(['#6d28d933', 0], ['#10101400', 55]),
        },
      ],
    },
    glass: bundledGlass(['panels'], {
      surfaceOpacity: 72,
      blur: 16,
      saturation: 160,
      borderOpacity: 30,
      shadow: 'none',
      radius: 'sm',
    }),
    icons: bundledIcons({ pack: 'phosphor', weight: 2 }),
  },
}

export const cyberLimeTheme = makeBundledTheme(spec)
