import { bundledGlassOff, bundledIcons, makeBundledTheme, type BundledThemeSpec } from './theme-builder'

/**
 * High Contrast — accessibility-oriented theme with strong boundaries,
 * maximized text contrast, and no transparency. Meets enhanced (AAA-level
 * where practical) contrast goals for text and control pairs.
 */
const spec: BundledThemeSpec = {
  id: 'high-contrast',
  name: 'High Contrast',
  light: {
    colors: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      cardForeground: '#0a0a0a',
      popover: '#ffffff',
      popoverForeground: '#0a0a0a',
      primary: '#0a0a0a',
      primaryForeground: '#ffffff',
      secondary: '#f0f0f0',
      secondaryForeground: '#0a0a0a',
      muted: '#f0f0f0',
      mutedForeground: '#3f3f3f',
      accent: '#e0e0e0',
      accentForeground: '#0a0a0a',
      destructive: '#b91c1c',
      border: '#525252',
      input: '#525252',
      ring: '#0a0a0a',
      sidebar: '#ffffff',
      sidebarForeground: '#0a0a0a',
      sidebarPrimary: '#0a0a0a',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#e0e0e0',
      sidebarAccentForeground: '#0a0a0a',
      sidebarBorder: '#525252',
      sidebarRing: '#0a0a0a',
      chart1: '#1d4ed8',
      chart2: '#047857',
      chart3: '#b45309',
      chart4: '#7e22ce',
      chart5: '#be123c',
    },
    editor: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      comment: '#3f3f3f',
      keyword: '#1e3a8a',
      keywordAccent: '#5b21b6',
      string: '#14532d',
      number: '#7c2d12',
      function: '#713f12',
      type: '#134e4a',
      variable: '#1f2937',
      constant: '#312e81',
      operator: '#171717',
      invalid: '#b91c1c',
      regexp: '#5b21b6',
      attribute: '#1f2937',
      tag: '#1e3a8a',
      escape: '#7c2d12',
    },
    canvas: {
      fallback: '#ffffff',
      layers: [],
    },
    glass: bundledGlassOff,
    icons: bundledIcons({ weight: 2.5 }),
  },
  dark: {
    colors: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#0f0f0f',
      cardForeground: '#ffffff',
      popover: '#0f0f0f',
      popoverForeground: '#ffffff',
      primary: '#ffffff',
      primaryForeground: '#000000',
      secondary: '#1a1a1a',
      secondaryForeground: '#ffffff',
      muted: '#1a1a1a',
      mutedForeground: '#d4d4d4',
      accent: '#262626',
      accentForeground: '#ffffff',
      destructive: '#fca5a5',
      border: '#8a8a8a',
      input: '#8a8a8a',
      ring: '#ffffff',
      sidebar: '#000000',
      sidebarForeground: '#ffffff',
      sidebarPrimary: '#ffffff',
      sidebarPrimaryForeground: '#000000',
      sidebarAccent: '#262626',
      sidebarAccentForeground: '#ffffff',
      sidebarBorder: '#8a8a8a',
      sidebarRing: '#ffffff',
      chart1: '#93c5fd',
      chart2: '#6ee7b7',
      chart3: '#fcd34d',
      chart4: '#d8b4fe',
      chart5: '#fda4af',
    },
    editor: {
      background: '#050505',
      foreground: '#ffffff',
      comment: '#c4c4c4',
      keyword: '#bfdbfe',
      keywordAccent: '#ddd6fe',
      string: '#bbf7d0',
      number: '#fed7aa',
      function: '#fde68a',
      type: '#99f6e4',
      variable: '#f4f4f5',
      constant: '#c7d2fe',
      operator: '#f5f5f5',
      invalid: '#fca5a5',
      regexp: '#ddd6fe',
      attribute: '#f4f4f5',
      tag: '#bfdbfe',
      escape: '#fed7aa',
    },
    canvas: {
      fallback: '#000000',
      layers: [],
    },
    glass: bundledGlassOff,
    icons: bundledIcons({ weight: 2.5 }),
  },
}

export const highContrastTheme = makeBundledTheme(spec)
