import {
  bundledGlass,
  bundledIcons,
  makeBundledTheme,
  stops,
  type BundledThemeSpec,
} from './theme-builder'

/**
 * Midnight Aurora — indigo/cyan aurora mesh with crystal glass.
 * Original palette inspired generically by aurora-night aesthetics.
 */
const spec: BundledThemeSpec = {
  id: 'midnight-aurora',
  name: 'Midnight Aurora',
  light: {
    colors: {
      background: '#f4f6fe',
      foreground: '#1b2140',
      card: '#ffffff',
      cardForeground: '#1b2140',
      popover: '#ffffff',
      popoverForeground: '#1b2140',
      primary: '#4c5fd5',
      primaryForeground: '#ffffff',
      secondary: '#e9edfb',
      secondaryForeground: '#2b3260',
      muted: '#eceffb',
      mutedForeground: '#5a6284',
      accent: '#e2e8fc',
      accentForeground: '#2b3260',
      destructive: '#c2344c',
      border: '#d5dcf4',
      input: '#d5dcf4',
      ring: '#4c5fd5',
      sidebar: '#eef1fc',
      sidebarForeground: '#1b2140',
      sidebarPrimary: '#4c5fd5',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#e2e8fc',
      sidebarAccentForeground: '#2b3260',
      sidebarBorder: '#d5dcf4',
      sidebarRing: '#4c5fd5',
      chart1: '#0891b2',
      chart2: '#4f46e5',
      chart3: '#059669',
      chart4: '#db2777',
      chart5: '#d97706',
    },
    editor: {
      background: '#f6f8ff',
      foreground: '#242c56',
      comment: '#7d86ad',
      keyword: '#4c5fd5',
      keywordAccent: '#8a4fd0',
      string: '#1f7a5c',
      number: '#9a5b16',
      function: '#7a6b1d',
      type: '#136f73',
      variable: '#43507e',
      constant: '#5c53c4',
      operator: '#4d5578',
      invalid: '#c2344c',
      regexp: '#8a4fd0',
      attribute: '#43507e',
      tag: '#4c5fd5',
      escape: '#8a6a2a',
    },
    canvas: {
      fallback: '#f4f6fe',
      layers: [
        {
          kind: 'radial',
          x: 18,
          y: 8,
          size: 'farthest-corner',
          stops: stops(['#33c7d480', 0], ['#f4f6fe00', 62]),
        },
        {
          kind: 'radial',
          x: 85,
          y: 92,
          size: 'farthest-side',
          stops: stops(['#8a7cf580', 0], ['#f4f6fe00', 70]),
        },
      ],
    },
    glass: bundledGlass(['sidebar', 'panels'], {
      surfaceOpacity: 72,
      blur: 16,
      saturation: 110,
      borderOpacity: 24,
    }),
  },
  dark: {
    colors: {
      background: '#0b0f1e',
      foreground: '#e6ebff',
      card: '#121830',
      cardForeground: '#e6ebff',
      popover: '#121830',
      popoverForeground: '#e6ebff',
      primary: '#7aa5ff',
      primaryForeground: '#0b0f1e',
      secondary: '#1a2138',
      secondaryForeground: '#d6defc',
      muted: '#1a2138',
      mutedForeground: '#9aa6d0',
      accent: '#222a4a',
      accentForeground: '#e6ebff',
      destructive: '#ff7d90',
      border: '#2a3352',
      input: '#2a3352',
      ring: '#7aa5ff',
      sidebar: '#0e1428',
      sidebarForeground: '#e6ebff',
      sidebarPrimary: '#7aa5ff',
      sidebarPrimaryForeground: '#0b0f1e',
      sidebarAccent: '#1a2138',
      sidebarAccentForeground: '#e6ebff',
      sidebarBorder: '#232c4d',
      sidebarRing: '#7aa5ff',
      chart1: '#22d3ee',
      chart2: '#818cf8',
      chart3: '#34d399',
      chart4: '#f472b6',
      chart5: '#fbbf24',
    },
    editor: {
      background: '#0d1326',
      foreground: '#dbe4ff',
      comment: '#6b76a8',
      keyword: '#9db4ff',
      keywordAccent: '#c4a5ff',
      string: '#7fd8c0',
      number: '#ffc98a',
      function: '#9fd0ff',
      type: '#7fe0d4',
      variable: '#c3cdf2',
      constant: '#b0a6ff',
      operator: '#8b95c4',
      invalid: '#ff8095',
      regexp: '#d0a5e8',
      attribute: '#a5c8ff',
      tag: '#9db4ff',
      escape: '#e0c9a5',
    },
    canvas: {
      fallback: '#0b0f1e',
      layers: [
        {
          kind: 'radial',
          x: 20,
          y: 0,
          size: 'farthest-corner',
          stops: stops(['#0e749099', 0], ['#0b0f1e00', 60]),
        },
        {
          kind: 'radial',
          x: 80,
          y: 100,
          size: 'farthest-corner',
          stops: stops(['#4338ca99', 0], ['#0b0f1e00', 65]),
        },
        {
          kind: 'linear',
          angle: 200,
          stops: stops(['#0b0f1e00', 35], ['#1e1b4b66', 100]),
        },
      ],
    },
    glass: bundledGlass(['sidebar', 'panels', 'overlays'], {
      surfaceOpacity: 58,
      blur: 24,
      saturation: 140,
      borderOpacity: 22,
      shadow: 'medium',
    }),
    icons: bundledIcons({ weight: 1.5 }),
  },
}

export const midnightAuroraTheme = makeBundledTheme(spec)
