import { bundledGlass, bundledIcons, makeBundledTheme, stops, type BundledThemeSpec } from './theme-builder'

/**
 * Nordic Frost — cool slate/ice palette with restrained frosted panels.
 * Original palette inspired generically by nordic-winter aesthetics.
 */
const spec: BundledThemeSpec = {
  id: 'nordic-frost',
  name: 'Nordic Frost',
  light: {
    colors: {
      background: '#f2f5f8',
      foreground: '#1e2530',
      card: '#ffffff',
      cardForeground: '#1e2530',
      popover: '#ffffff',
      popoverForeground: '#1e2530',
      primary: '#2f5a7a',
      primaryForeground: '#ffffff',
      secondary: '#e6ecf2',
      secondaryForeground: '#2a3a4a',
      muted: '#e9eef3',
      mutedForeground: '#55606e',
      accent: '#dde7ef',
      accentForeground: '#2a3a4a',
      destructive: '#b3423f',
      border: '#ccd7e0',
      input: '#ccd7e0',
      ring: '#2f5a7a',
      sidebar: '#ebf0f5',
      sidebarForeground: '#1e2530',
      sidebarPrimary: '#2f5a7a',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#dde7ef',
      sidebarAccentForeground: '#2a3a4a',
      sidebarBorder: '#ccd7e0',
      sidebarRing: '#2f5a7a',
      chart1: '#2f6f8f',
      chart2: '#5d8f6a',
      chart3: '#8a6d3b',
      chart4: '#7a5c8f',
      chart5: '#b35c50',
    },
    editor: {
      background: '#f4f7fa',
      foreground: '#242e3a',
      comment: '#7a8794',
      keyword: '#2f6f8f',
      keywordAccent: '#6a5a9e',
      string: '#3d7358',
      number: '#8a5a28',
      function: '#6b6b3a',
      type: '#2f7370',
      variable: '#44505c',
      constant: '#4a5f8a',
      operator: '#4a545e',
      invalid: '#b3423f',
      regexp: '#6a5a9e',
      attribute: '#44505c',
      tag: '#2f6f8f',
      escape: '#7a5c34',
    },
    canvas: {
      fallback: '#f2f5f8',
      layers: [
        {
          kind: 'linear',
          angle: 180,
          stops: stops(['#f2f5f8', 0], ['#e7edf3', 100]),
        },
      ],
    },
    glass: bundledGlass(['sidebar', 'panels'], {
      surfaceOpacity: 78,
      blur: 14,
      saturation: 105,
      borderOpacity: 22,
      shadow: 'none',
      radius: 'sm',
    }),
  },
  dark: {
    colors: {
      background: '#10161d',
      foreground: '#e2e8f0',
      card: '#171e26',
      cardForeground: '#e2e8f0',
      popover: '#171e26',
      popoverForeground: '#e2e8f0',
      primary: '#8fb8d8',
      primaryForeground: '#10161d',
      secondary: '#1f2833',
      secondaryForeground: '#cfd9e4',
      muted: '#1f2833',
      mutedForeground: '#93a1b0',
      accent: '#27323f',
      accentForeground: '#e2e8f0',
      destructive: '#ef8a84',
      border: '#2b3644',
      input: '#2b3644',
      ring: '#8fb8d8',
      sidebar: '#141b23',
      sidebarForeground: '#e2e8f0',
      sidebarPrimary: '#8fb8d8',
      sidebarPrimaryForeground: '#10161d',
      sidebarAccent: '#1f2833',
      sidebarAccentForeground: '#e2e8f0',
      sidebarBorder: '#242e3b',
      sidebarRing: '#8fb8d8',
      chart1: '#6fb3d8',
      chart2: '#82c08f',
      chart3: '#c9a86a',
      chart4: '#a98cc9',
      chart5: '#d88a80',
    },
    editor: {
      background: '#131a22',
      foreground: '#d7e0e9',
      comment: '#6d7a87',
      keyword: '#7fb3d4',
      keywordAccent: '#a291d6',
      string: '#7bb894',
      number: '#d0a06a',
      function: '#c2c491',
      type: '#72b8b2',
      variable: '#b7c2cd',
      constant: '#93a8d6',
      operator: '#93a0ad',
      invalid: '#ef8a84',
      regexp: '#a291d6',
      attribute: '#b7c2cd',
      tag: '#7fb3d4',
      escape: '#c9ab7c',
    },
    canvas: {
      fallback: '#10161d',
      layers: [
        {
          kind: 'radial',
          x: 50,
          y: 0,
          size: 'farthest-corner',
          stops: stops(['#1d3a4d66', 0], ['#10161d00', 70]),
        },
      ],
    },
    glass: bundledGlass(['sidebar'], {
      surfaceOpacity: 80,
      blur: 12,
      saturation: 105,
      borderOpacity: 20,
      shadow: 'none',
      radius: 'sm',
    }),
    icons: bundledIcons({ pack: 'tabler' }),
  },
}

export const nordicFrostTheme = makeBundledTheme(spec)
