import { bundledGlass, bundledIcons, makeBundledTheme, stops, type BundledThemeSpec } from './theme-builder'

/**
 * Ocean Depths — deep teal/blue surfaces with luminous accents.
 * Original palette inspired generically by deep-sea aesthetics.
 */
const spec: BundledThemeSpec = {
  id: 'ocean-depths',
  name: 'Ocean Depths',
  light: {
    colors: {
      background: '#eef6f9',
      foreground: '#0f2430',
      card: '#ffffff',
      cardForeground: '#0f2430',
      popover: '#ffffff',
      popoverForeground: '#0f2430',
      primary: '#0e7490',
      primaryForeground: '#ffffff',
      secondary: '#dceef4',
      secondaryForeground: '#134e5e',
      muted: '#e2f0f5',
      mutedForeground: '#4c6b78',
      accent: '#cfe8f0',
      accentForeground: '#134e5e',
      destructive: '#b3423f',
      border: '#c8dde5',
      input: '#c8dde5',
      ring: '#0e7490',
      sidebar: '#e4f0f5',
      sidebarForeground: '#0f2430',
      sidebarPrimary: '#0e7490',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#cfe8f0',
      sidebarAccentForeground: '#134e5e',
      sidebarBorder: '#c8dde5',
      sidebarRing: '#0e7490',
      chart1: '#0891b2',
      chart2: '#0d9488',
      chart3: '#4f46e5',
      chart4: '#d97706',
      chart5: '#be185d',
    },
    editor: {
      background: '#f2f9fc',
      foreground: '#16303e',
      comment: '#6f8a96',
      keyword: '#0e7490',
      keywordAccent: '#6d5aa8',
      string: '#2a7a58',
      number: '#9a5a28',
      function: '#6b6a2a',
      type: '#0f7a74',
      variable: '#3c5560',
      constant: '#4a5f9e',
      operator: '#44585f',
      invalid: '#b3423f',
      regexp: '#6d5aa8',
      attribute: '#3c5560',
      tag: '#0e7490',
      escape: '#7a5c34',
    },
    canvas: {
      fallback: '#eef6f9',
      layers: [
        {
          kind: 'linear',
          angle: 190,
          stops: stops(['#d8ecf4', 0], ['#eef6f9', 70]),
        },
      ],
    },
    glass: bundledGlass(['sidebar', 'overlays'], {
      surfaceOpacity: 68,
      blur: 20,
      saturation: 125,
      borderOpacity: 22,
      shadow: 'medium',
    }),
  },
  dark: {
    colors: {
      background: '#06121c',
      foreground: '#dfeef5',
      card: '#0b1b28',
      cardForeground: '#dfeef5',
      popover: '#0b1b28',
      popoverForeground: '#dfeef5',
      primary: '#5ecbdd',
      primaryForeground: '#06121c',
      secondary: '#102634',
      secondaryForeground: '#c2e0ec',
      muted: '#0f2231',
      mutedForeground: '#8fb0c2',
      accent: '#16303f',
      accentForeground: '#dfeef5',
      destructive: '#f08080',
      border: '#1e3a4c',
      input: '#1e3a4c',
      ring: '#5ecbdd',
      sidebar: '#091622',
      sidebarForeground: '#dfeef5',
      sidebarPrimary: '#5ecbdd',
      sidebarPrimaryForeground: '#06121c',
      sidebarAccent: '#102634',
      sidebarAccentForeground: '#dfeef5',
      sidebarBorder: '#193344',
      sidebarRing: '#5ecbdd',
      chart1: '#22d3ee',
      chart2: '#2dd4bf',
      chart3: '#818cf8',
      chart4: '#fbbf24',
      chart5: '#f472b6',
    },
    editor: {
      background: '#081626',
      foreground: '#d4e8f2',
      comment: '#5f7d90',
      keyword: '#63c8e0',
      keywordAccent: '#a08fe0',
      string: '#6ec8a0',
      number: '#e0a860',
      function: '#8ac8d8',
      type: '#66c4b8',
      variable: '#b0ccd8',
      constant: '#9aa8e8',
      operator: '#7d94a2',
      invalid: '#f08080',
      regexp: '#a08fe0',
      attribute: '#b0ccd8',
      tag: '#63c8e0',
      escape: '#d0b080',
    },
    canvas: {
      fallback: '#06121c',
      layers: [
        {
          kind: 'radial',
          x: 25,
          y: 0,
          size: 'farthest-corner',
          stops: stops(['#0e5d7566', 0], ['#06121c00', 60]),
        },
        {
          kind: 'radial',
          x: 75,
          y: 100,
          size: 'farthest-corner',
          stops: stops(['#1e3a8a55', 0], ['#06121c00', 62]),
        },
      ],
    },
    glass: bundledGlass(['sidebar', 'panels', 'overlays'], {
      surfaceOpacity: 62,
      blur: 24,
      saturation: 130,
      borderOpacity: 22,
      shadow: 'medium',
    }),
    icons: bundledIcons({ pack: 'tabler', weight: 1.5 }),
  },
}

export const oceanDepthsTheme = makeBundledTheme(spec)
