import { bundledGlass, bundledIcons, makeBundledTheme, stops, type BundledThemeSpec } from './theme-builder'

/**
 * Rose Quartz — soft rose/lilac editorial palette.
 * Original palette inspired generically by blush/editorial aesthetics.
 */
const spec: BundledThemeSpec = {
  id: 'rose-quartz',
  name: 'Rose Quartz',
  light: {
    colors: {
      background: '#faf5f7',
      foreground: '#322229',
      card: '#ffffff',
      cardForeground: '#322229',
      popover: '#ffffff',
      popoverForeground: '#322229',
      primary: '#a34468',
      primaryForeground: '#ffffff',
      secondary: '#f4e7ec',
      secondaryForeground: '#6d2c44',
      muted: '#f3e8ec',
      mutedForeground: '#6d5560',
      accent: '#efdde4',
      accentForeground: '#6d2c44',
      destructive: '#b03050',
      border: '#e8d5dc',
      input: '#e8d5dc',
      ring: '#a34468',
      sidebar: '#f5ecef',
      sidebarForeground: '#322229',
      sidebarPrimary: '#a34468',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#efdde4',
      sidebarAccentForeground: '#6d2c44',
      sidebarBorder: '#e8d5dc',
      sidebarRing: '#a34468',
      chart1: '#c2577e',
      chart2: '#8f6aaf',
      chart3: '#c98a4b',
      chart4: '#5f8f7a',
      chart5: '#b05252',
    },
    editor: {
      background: '#fcf7f9',
      foreground: '#3a2830',
      comment: '#9c828c',
      keyword: '#a34468',
      keywordAccent: '#8a5aa8',
      string: '#587a54',
      number: '#a05a34',
      function: '#8a6a3a',
      type: '#3a7a78',
      variable: '#584648',
      constant: '#6a5aa8',
      operator: '#6a5a5e',
      invalid: '#b03050',
      regexp: '#8a5aa8',
      attribute: '#584648',
      tag: '#a34468',
      escape: '#8a6a44',
    },
    canvas: {
      fallback: '#faf5f7',
      layers: [
        {
          kind: 'radial',
          x: 12,
          y: 10,
          size: 'farthest-side',
          stops: stops(['#f0c4d480', 0], ['#faf5f700', 65]),
        },
        {
          kind: 'radial',
          x: 88,
          y: 90,
          size: 'farthest-side',
          stops: stops(['#d8c0f080', 0], ['#faf5f700', 65]),
        },
      ],
    },
    glass: bundledGlass(['sidebar', 'panels', 'overlays'], {
      surfaceOpacity: 62,
      blur: 22,
      saturation: 120,
      borderOpacity: 20,
      radius: 'lg',
    }),
    icons: bundledIcons({ pack: 'phosphor', weight: 1.5 }),
  },
  dark: {
    colors: {
      background: '#1d1418',
      foreground: '#f4e8ec',
      card: '#271a20',
      cardForeground: '#f4e8ec',
      popover: '#271a20',
      popoverForeground: '#f4e8ec',
      primary: '#e5a0b8',
      primaryForeground: '#1d1418',
      secondary: '#33222a',
      secondaryForeground: '#edd7df',
      muted: '#2d1f26',
      mutedForeground: '#b998a4',
      accent: '#3d2931',
      accentForeground: '#f4e8ec',
      destructive: '#f2809a',
      border: '#43303a',
      input: '#43303a',
      ring: '#e5a0b8',
      sidebar: '#231820',
      sidebarForeground: '#f4e8ec',
      sidebarPrimary: '#e5a0b8',
      sidebarPrimaryForeground: '#1d1418',
      sidebarAccent: '#33222a',
      sidebarAccentForeground: '#f4e8ec',
      sidebarBorder: '#3b2a33',
      sidebarRing: '#e5a0b8',
      chart1: '#e07ba0',
      chart2: '#a98cd0',
      chart3: '#d8a86a',
      chart4: '#7ab8a0',
      chart5: '#d87a7a',
    },
    editor: {
      background: '#22161c',
      foreground: '#eedce3',
      comment: '#96808a',
      keyword: '#eaa8c0',
      keywordAccent: '#c0a0e8',
      string: '#9ec48a',
      number: '#e8a878',
      function: '#e0c48a',
      type: '#84c4bc',
      variable: '#d8c2c8',
      constant: '#b0a0e8',
      operator: '#ab959e',
      invalid: '#f2809a',
      regexp: '#c0a0e8',
      attribute: '#d8c2c8',
      tag: '#eaa8c0',
      escape: '#d8b888',
    },
    canvas: {
      fallback: '#1d1418',
      layers: [
        {
          kind: 'radial',
          x: 15,
          y: 8,
          size: 'farthest-corner',
          stops: stops(['#7a2c4866', 0], ['#1d141800', 60]),
        },
        {
          kind: 'radial',
          x: 85,
          y: 95,
          size: 'farthest-corner',
          stops: stops(['#4c2c6b66', 0], ['#1d141800', 62]),
        },
      ],
    },
    glass: bundledGlass(['sidebar', 'panels', 'overlays'], {
      surfaceOpacity: 58,
      blur: 22,
      saturation: 120,
      borderOpacity: 20,
      radius: 'lg',
    }),
    icons: bundledIcons({ pack: 'phosphor', weight: 1.5 }),
  },
}

export const roseQuartzTheme = makeBundledTheme(spec)
