import { bundledGlass, makeBundledTheme, stops, type BundledThemeSpec } from './theme-builder'

/**
 * Solar Flare — warm amber/coral gradients with high-energy accents.
 * Original palette inspired generically by sunset aesthetics.
 */
const spec: BundledThemeSpec = {
  id: 'solar-flare',
  name: 'Solar Flare',
  light: {
    colors: {
      background: '#fdf6ee',
      foreground: '#2b1d12',
      card: '#ffffff',
      cardForeground: '#2b1d12',
      popover: '#ffffff',
      popoverForeground: '#2b1d12',
      primary: '#c2410c',
      primaryForeground: '#ffffff',
      secondary: '#f9e9d8',
      secondaryForeground: '#7c3a12',
      muted: '#f7ecdd',
      mutedForeground: '#6b5847',
      accent: '#fbe3c8',
      accentForeground: '#7c3a12',
      destructive: '#b91c1c',
      border: '#ecd9c2',
      input: '#ecd9c2',
      ring: '#c2410c',
      sidebar: '#f9efe2',
      sidebarForeground: '#2b1d12',
      sidebarPrimary: '#c2410c',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#fbe3c8',
      sidebarAccentForeground: '#7c3a12',
      sidebarBorder: '#ecd9c2',
      sidebarRing: '#c2410c',
      chart1: '#ea7317',
      chart2: '#c2410c',
      chart3: '#ca8a04',
      chart4: '#be123c',
      chart5: '#65a30d',
    },
    editor: {
      background: '#fefaf4',
      foreground: '#33241a',
      comment: '#96826f',
      keyword: '#b34710',
      keywordAccent: '#a03b74',
      string: '#587a2a',
      number: '#a05a1e',
      function: '#8a6a1e',
      type: '#1f7a6a',
      variable: '#55483a',
      constant: '#8a5a9e',
      operator: '#5f5347',
      invalid: '#b91c1c',
      regexp: '#a03b74',
      attribute: '#55483a',
      tag: '#b34710',
      escape: '#8a6a2a',
    },
    canvas: {
      fallback: '#fdf6ee',
      layers: [
        {
          kind: 'linear',
          angle: 160,
          stops: stops(['#fde8c8', 0], ['#fdf6ee', 55]),
        },
        {
          kind: 'radial',
          x: 90,
          y: 10,
          size: 'farthest-side',
          stops: stops(['#fb923c40', 0], ['#fdf6ee00', 60]),
        },
      ],
    },
    glass: bundledGlass(['panels', 'overlays'], {
      surfaceOpacity: 68,
      blur: 20,
      saturation: 150,
      borderOpacity: 26,
      shadow: 'medium',
    }),
  },
  dark: {
    colors: {
      background: '#1c1109',
      foreground: '#f5ead9',
      card: '#241710',
      cardForeground: '#f5ead9',
      popover: '#241710',
      popoverForeground: '#f5ead9',
      primary: '#fbbf24',
      primaryForeground: '#1c1109',
      secondary: '#31200f',
      secondaryForeground: '#f3ddba',
      muted: '#2b1c0e',
      mutedForeground: '#b39b7f',
      accent: '#3a2611',
      accentForeground: '#f5ead9',
      destructive: '#f87171',
      border: '#452e15',
      input: '#452e15',
      ring: '#fbbf24',
      sidebar: '#221510',
      sidebarForeground: '#f5ead9',
      sidebarPrimary: '#fbbf24',
      sidebarPrimaryForeground: '#1c1109',
      sidebarAccent: '#31200f',
      sidebarAccentForeground: '#f5ead9',
      sidebarBorder: '#3b2814',
      sidebarRing: '#fbbf24',
      chart1: '#fb923c',
      chart2: '#f43f5e',
      chart3: '#facc15',
      chart4: '#f97316',
      chart5: '#fda4af',
    },
    editor: {
      background: '#201409',
      foreground: '#f0e3cd',
      comment: '#96826b',
      keyword: '#f7b25c',
      keywordAccent: '#e58fb1',
      string: '#b9c46a',
      number: '#f2a35c',
      function: '#e8c46a',
      type: '#7cc4a4',
      variable: '#d8c8ae',
      constant: '#cf9df0',
      operator: '#b8a58c',
      invalid: '#f87171',
      regexp: '#e58fb1',
      attribute: '#d8c8ae',
      tag: '#f7b25c',
      escape: '#e0c088',
    },
    canvas: {
      fallback: '#1c1109',
      layers: [
        {
          kind: 'linear',
          angle: 170,
          stops: stops(['#311505', 0], ['#1c1109', 60]),
        },
        {
          kind: 'radial',
          x: 85,
          y: 8,
          size: 'farthest-corner',
          stops: stops(['#c2410c55', 0], ['#1c110900', 55]),
        },
      ],
    },
    glass: bundledGlass(['panels', 'overlays'], {
      surfaceOpacity: 64,
      blur: 22,
      saturation: 150,
      borderOpacity: 24,
      shadow: 'medium',
    }),
  },
}

export const solarFlareTheme = makeBundledTheme(spec)
